// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Arithm
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 0 " "

# 8 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | ABS
  | RBR
  | LBR
  | EQ
  | KW_PRINT
  | VNAME of (string)
  | BIN
  | POW
  | REM
  | DIV
  | MUL
  | SUB
  | SUM
  | NUM of (BigInt.BigInt)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_ABS
    | TOKEN_RBR
    | TOKEN_LBR
    | TOKEN_EQ
    | TOKEN_KW_PRINT
    | TOKEN_VNAME
    | TOKEN_BIN
    | TOKEN_POW
    | TOKEN_REM
    | TOKEN_DIV
    | TOKEN_MUL
    | TOKEN_SUB
    | TOKEN_SUM
    | TOKEN_NUM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_stmtAnalyser
    | NONTERM_stmt
    | NONTERM_expr
    | NONTERM_rexpr
    | NONTERM_baseAndPow
    | NONTERM_power
    | NONTERM_vname
    | NONTERM_eof

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | ABS  -> 1 
  | RBR  -> 2 
  | LBR  -> 3 
  | EQ  -> 4 
  | KW_PRINT  -> 5 
  | VNAME _ -> 6 
  | BIN  -> 7 
  | POW  -> 8 
  | REM  -> 9 
  | DIV  -> 10 
  | MUL  -> 11 
  | SUB  -> 12 
  | SUM  -> 13 
  | NUM _ -> 14 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_ABS 
  | 2 -> TOKEN_RBR 
  | 3 -> TOKEN_LBR 
  | 4 -> TOKEN_EQ 
  | 5 -> TOKEN_KW_PRINT 
  | 6 -> TOKEN_VNAME 
  | 7 -> TOKEN_BIN 
  | 8 -> TOKEN_POW 
  | 9 -> TOKEN_REM 
  | 10 -> TOKEN_DIV 
  | 11 -> TOKEN_MUL 
  | 12 -> TOKEN_SUB 
  | 13 -> TOKEN_SUM 
  | 14 -> TOKEN_NUM 
  | 17 -> TOKEN_end_of_input
  | 15 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_start 
    | 3 -> NONTERM_stmtAnalyser 
    | 4 -> NONTERM_stmt 
    | 5 -> NONTERM_stmt 
    | 6 -> NONTERM_expr 
    | 7 -> NONTERM_expr 
    | 8 -> NONTERM_expr 
    | 9 -> NONTERM_rexpr 
    | 10 -> NONTERM_rexpr 
    | 11 -> NONTERM_rexpr 
    | 12 -> NONTERM_rexpr 
    | 13 -> NONTERM_baseAndPow 
    | 14 -> NONTERM_baseAndPow 
    | 15 -> NONTERM_power 
    | 16 -> NONTERM_power 
    | 17 -> NONTERM_power 
    | 18 -> NONTERM_power 
    | 19 -> NONTERM_power 
    | 20 -> NONTERM_vname 
    | 21 -> NONTERM_eof 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 17 
let _fsyacc_tagOfErrorTerminal = 15

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | ABS  -> "ABS" 
  | RBR  -> "RBR" 
  | LBR  -> "LBR" 
  | EQ  -> "EQ" 
  | KW_PRINT  -> "KW_PRINT" 
  | VNAME _ -> "VNAME" 
  | BIN  -> "BIN" 
  | POW  -> "POW" 
  | REM  -> "REM" 
  | DIV  -> "DIV" 
  | MUL  -> "MUL" 
  | SUB  -> "SUB" 
  | SUM  -> "SUM" 
  | NUM _ -> "NUM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | ABS  -> (null : System.Object) 
  | RBR  -> (null : System.Object) 
  | LBR  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | KW_PRINT  -> (null : System.Object) 
  | VNAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | BIN  -> (null : System.Object) 
  | POW  -> (null : System.Object) 
  | REM  -> (null : System.Object) 
  | DIV  -> (null : System.Object) 
  | MUL  -> (null : System.Object) 
  | SUB  -> (null : System.Object) 
  | SUM  -> (null : System.Object) 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 2us; 65535us; 0us; 1us; 2us; 3us; 0us; 65535us; 2us; 65535us; 0us; 2us; 2us; 2us; 4us; 65535us; 7us; 8us; 27us; 10us; 29us; 11us; 33us; 12us; 6us; 65535us; 7us; 9us; 13us; 14us; 15us; 16us; 27us; 9us; 29us; 9us; 33us; 9us; 9us; 65535us; 7us; 17us; 13us; 17us; 15us; 17us; 18us; 19us; 20us; 21us; 22us; 23us; 27us; 17us; 29us; 17us; 33us; 17us; 10us; 65535us; 7us; 24us; 13us; 24us; 15us; 24us; 18us; 24us; 20us; 24us; 22us; 24us; 25us; 26us; 27us; 24us; 29us; 24us; 33us; 24us; 13us; 65535us; 0us; 6us; 2us; 6us; 4us; 5us; 7us; 32us; 13us; 32us; 15us; 32us; 18us; 32us; 20us; 32us; 22us; 32us; 25us; 32us; 27us; 32us; 29us; 32us; 33us; 32us; 0us; 65535us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 4us; 5us; 8us; 13us; 20us; 30us; 41us; 55us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 2us; 1us; 2us; 1us; 4us; 1us; 4us; 1us; 5us; 1us; 5us; 3us; 5us; 7us; 8us; 4us; 6us; 10us; 11us; 12us; 3us; 7us; 8us; 15us; 3us; 7us; 8us; 16us; 3us; 7us; 8us; 19us; 1us; 7us; 4us; 7us; 10us; 11us; 12us; 1us; 8us; 4us; 8us; 10us; 11us; 12us; 2us; 9us; 14us; 1us; 10us; 2us; 10us; 14us; 1us; 11us; 2us; 11us; 14us; 1us; 12us; 2us; 12us; 14us; 1us; 13us; 1us; 14us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 16us; 1us; 16us; 1us; 17us; 1us; 18us; 1us; 19us; 1us; 20us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 9us; 11us; 13us; 15us; 17us; 21us; 26us; 30us; 34us; 38us; 40us; 45us; 47us; 52us; 55us; 57us; 60us; 62us; 65us; 67us; 70us; 72us; 74us; 76us; 78us; 80us; 82us; 84us; 86us; 88us; 90us; |]
let _fsyacc_action_rows = 35
let _fsyacc_actionTableElements = [|2us; 32768us; 5us; 4us; 6us; 34us; 0us; 49152us; 2us; 16385us; 5us; 4us; 6us; 34us; 0us; 16386us; 1us; 32768us; 6us; 34us; 0us; 16388us; 1us; 32768us; 4us; 7us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 2us; 16389us; 12us; 15us; 13us; 13us; 3us; 16390us; 9us; 22us; 10us; 20us; 11us; 18us; 3us; 32768us; 2us; 28us; 12us; 15us; 13us; 13us; 3us; 32768us; 1us; 30us; 12us; 15us; 13us; 13us; 2us; 16403us; 12us; 15us; 13us; 13us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 3us; 16391us; 9us; 22us; 10us; 20us; 11us; 18us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 3us; 16392us; 9us; 22us; 10us; 20us; 11us; 18us; 1us; 16393us; 8us; 25us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 1us; 16394us; 8us; 25us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 1us; 16395us; 8us; 25us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 1us; 16396us; 8us; 25us; 0us; 16397us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 0us; 16398us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 0us; 16399us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 0us; 16400us; 0us; 16401us; 0us; 16402us; 5us; 32768us; 1us; 29us; 3us; 27us; 6us; 34us; 7us; 33us; 14us; 31us; 0us; 16404us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 7us; 8us; 10us; 11us; 13us; 19us; 22us; 26us; 30us; 34us; 37us; 43us; 47us; 53us; 57us; 59us; 65us; 67us; 73us; 75us; 81us; 83us; 84us; 90us; 91us; 97us; 98us; 104us; 105us; 106us; 107us; 113us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 2us; 1us; 2us; 3us; 1us; 3us; 3us; 1us; 3us; 3us; 3us; 1us; 3us; 3us; 3us; 1us; 1us; 2us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 2us; 3us; 3us; 4us; 4us; 4us; 5us; 5us; 5us; 5us; 6us; 6us; 7us; 7us; 7us; 7us; 7us; 8us; 9us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16386us; 65535us; 16388us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16397us; 65535us; 16398us; 65535us; 16399us; 65535us; 16400us; 16401us; 16402us; 65535us; 16404us; |]
let _fsyacc_reductions ()  =    [| 
# 177 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  AST.Program )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 186 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 "Parser.fsy"
                                  [_1]
                   )
# 24 "Parser.fsy"
                 :  AST.Program ));
# 197 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmt)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data :  AST.Program )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 "Parser.fsy"
                                        _1 :: _2
                   )
# 25 "Parser.fsy"
                 :  AST.Program ));
# 209 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "Parser.fsy"
                                         _1
                   )
# 27 "Parser.fsy"
                 : 'stmtAnalyser));
# 220 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'vname)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "Parser.fsy"
                                           Arithm.AST.Print(_2)
                   )
# 29 "Parser.fsy"
                 : 'stmt));
# 231 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'vname)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "Parser.fsy"
                                          Arithm.AST.VDecl(_1,_3)
                   )
# 30 "Parser.fsy"
                 : 'stmt));
# 243 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "Parser.fsy"
                                  _1
                   )
# 32 "Parser.fsy"
                 : 'expr));
# 254 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'rexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "Parser.fsy"
                                           Arithm.AST.Sum(_1, _3)
                   )
# 33 "Parser.fsy"
                 : 'expr));
# 266 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'rexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "Parser.fsy"
                                           Arithm.AST.Sub(_1, _3)
                   )
# 34 "Parser.fsy"
                 : 'expr));
# 278 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'baseAndPow)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "Parser.fsy"
                                        _1
                   )
# 36 "Parser.fsy"
                 : 'rexpr));
# 289 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rexpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'baseAndPow)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "Parser.fsy"
                                                 Arithm.AST.Mul(_1, _3)
                   )
# 37 "Parser.fsy"
                 : 'rexpr));
# 301 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rexpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'baseAndPow)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "Parser.fsy"
                                                 Arithm.AST.Div(_1, _3)
                   )
# 38 "Parser.fsy"
                 : 'rexpr));
# 313 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rexpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'baseAndPow)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "Parser.fsy"
                                                 Arithm.AST.Rem(_1, _3)
                   )
# 39 "Parser.fsy"
                 : 'rexpr));
# 325 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'power)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "Parser.fsy"
                                        _1
                   )
# 41 "Parser.fsy"
                 : 'baseAndPow));
# 336 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'baseAndPow)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'power)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "Parser.fsy"
                                                 Arithm.AST.Pow(_1, _3)
                   )
# 42 "Parser.fsy"
                 : 'baseAndPow));
# 348 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "Parser.fsy"
                                          _2
                   )
# 44 "Parser.fsy"
                 : 'power));
# 359 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "Parser.fsy"
                                         Arithm.AST.Abs _2
                   )
# 45 "Parser.fsy"
                 : 'power));
# 370 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : BigInt.BigInt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "Parser.fsy"
                                Arithm.AST.Num(_1)
                   )
# 46 "Parser.fsy"
                 : 'power));
# 381 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'vname)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "Parser.fsy"
                                  Arithm.AST.NVar(_1)
                   )
# 47 "Parser.fsy"
                 : 'power));
# 392 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "Parser.fsy"
                                     Arithm.AST.Bin _2
                   )
# 48 "Parser.fsy"
                 : 'power));
# 403 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "Parser.fsy"
                                   Arithm.AST.Var(_1)
                   )
# 50 "Parser.fsy"
                 : 'vname));
# 414 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "Parser.fsy"
                               1
                   )
# 52 "Parser.fsy"
                 : 'eof));
|]
# 425 "Parser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 18;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  AST.Program  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
